name = "webdavx"
compatibility_date = "2024-01-01"

pages_build_output_dir = "build"

[env.production]
vars = { WEBDAV_USERNAME = "XCQ0607", WEBDAV_PASSWORD = "1234567890Xyz@", WEBDAV_PUBLIC_READ = "1" }

# 注意：部署后需要在 Cloudflare Pages 控制台手动绑定 R2 bucket 到 BUCKET 变量
# R2 绑定无法通过 wrangler.toml 完全配置，需要在控制台操作

